// Generated by CoffeeScript 1.4.0
(function() {
  var collections, mongo, remotemodel, _;

  _ = require('underscore');

  mongo = require('./mongodb');

  _.extend(exports, collections = require('../index'));

  exports.remotemodel = remotemodel = require('../remotemodel');

  exports.MongoCollection = mongo.MongoCollection.extend4000(collections.ModelMixin, collections.ReferenceMixin, collections.RequestIdMixin, collections.CachingMixin);

}).call(this);
